name: LKS Telemedicine Auto Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Hanya akan jalan jika ada perubahan di folder backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🐿️ Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 🔨 Build SAM Application
        run: sam build

      - name: 🚀 Deploy to AWS
        run: |
          sam deploy \
            --stack-name lks-telemedicine \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --region us-east-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
